{
 "title": "Victron TIG",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "EVN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vebus",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Connected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "State",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Battery",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mains Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Mains" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bulk Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Bulk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Inverter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Absorption Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Absorption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Float Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LowBattery Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "LowBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overload Led",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Leds",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$ServerName$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Overload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter mode history",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Inverter State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "State",
     "select": [
      [
       { "params": [ "State" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 3 },
   "targets": [
    {
     "alias": "EVN_Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Voltage (V)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "ActiveIn" }
     ]
    },
    {
     "alias": "EVN_Voltage_1m_avg",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Voltage (V)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "ActiveIn" }
     ]
    }
   ]
  },
  {
   "title": "SOC % And Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery Charge (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Charge (%)" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Battery Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Dc" }
     ]
    }
   ]
  },
  {
   "title": "Battery Cells Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "MaxCellVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max Cell Voltage (V)" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "MinCellVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Min Cell Voltage (V)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid AC Input (10s resolution)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "AC In (Watts)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (Watts)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "ActiveIn" }
     ]
    },
    {
     "alias": "AC In (Amps)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current(Amps)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "ActiveIn" }
     ]
    }
   ]
  },
  {
   "title": "Inverter AC Output (10s resolution)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 14 },
   "targets": [
    {
     "alias": "Ac Out (Watts)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Power (Watts)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "Out" }
     ]
    },
    {
     "alias": "Ac Out (Amps)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current(Amps)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Ac" },
      { "condition": "AND", "key": "line_type", "operator": "=", "value": "Out" }
     ]
    }
   ]
  },
  {
   "title": "Battery Consumption In/Out (Negative is output)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "alias": "V-Tac Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Dc" }
     ]
    },
    {
     "alias": "V-Tac Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Power" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "current_type", "operator": "=", "value": "Dc" }
     ]
    }
   ]
  }
 ]
}